# coding: utf-8
#
# Copyright 2023-2024 :Barry-Thomas-Paul: Moss
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Enum
# this is a auto generated file generated by Cheetah
# Namespace: com.sun.star.security
# Libre Office Version: 2024.2
from __future__ import annotations
from typing import Protocol, Any
from typing_extensions import Literal


class ExtAltNameTypeProto(Protocol):
    """Protocol for ExtAltNameType"""

    @property
    def typeName(self) -> Literal["com.sun.star.security.ExtAltNameType"]:
        ...
    value: Any
    DIRECTORY_NAME: ExtAltNameTypeProto
    DNS_NAME: ExtAltNameTypeProto
    EDI_PARTY_NAME: ExtAltNameTypeProto
    IP_ADDRESS: ExtAltNameTypeProto
    OTHER_NAME: ExtAltNameTypeProto
    REGISTERED_ID: ExtAltNameTypeProto
    RFC822_NAME: ExtAltNameTypeProto
    URL: ExtAltNameTypeProto
    X400_ADDRESS: ExtAltNameTypeProto

DIRECTORY_NAME: ExtAltNameTypeProto
"""
Currently unsupported.
"""
DNS_NAME: ExtAltNameTypeProto
"""
The entry contains a dns name.

The value of CertAltNameEntry contains a OUString.
"""
EDI_PARTY_NAME: ExtAltNameTypeProto
"""
Currently unsupported.
"""
IP_ADDRESS: ExtAltNameTypeProto
"""
The entry contains an IP address.

The value of CertAltNameEntry contains a Sequence of sal_Int8.
"""
OTHER_NAME: ExtAltNameTypeProto
"""
Customize name/value pair The value of CertAltNameEntry contains a NamedValue.
"""
REGISTERED_ID: ExtAltNameTypeProto
"""
The entry contains a registered id.

The value of CertAltNameEntry contains a OUString.
"""
RFC822_NAME: ExtAltNameTypeProto
"""
The entry contains rfc822 name.

The value of CertAltNameEntry contains an OUString.
"""
URL: ExtAltNameTypeProto
"""
The entry contains a URL.

The value of CertAltNameEntry contains a OUString.
"""
X400_ADDRESS: ExtAltNameTypeProto
"""
Currently unsupported.
"""

