# coding: utf-8
#
# Copyright 2023 :Barry-Thomas-Paul: Moss
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Enum
# this is a auto generated file generated by Cheetah
# Namespace: com.sun.star.chart2
# Libre Office Version: 7.4
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    import uno
from enum import Enum

class SymbolStyle(Enum):
    """
    Enum

    

    See Also:
        `API SymbolStyle <https://api.libreoffice.org/docs/idl/ref/namespacecom_1_1sun_1_1star_1_1chart2.html#a8068445d248b830d1708dcb2a2afb2c6>`_
    """
    typeName: str = 'com.sun.star.chart2.SymbolStyle'

    AUTO: 'uno.Enum'
    """
    The symbol is taken automatically.
    """
    GRAPHIC: 'uno.Enum'
    """
    uses the graphic given in Symbol.Graphic as symbol.
    """
    NONE: 'uno.Enum'
    """
    Default, no pies are exploded.
    
    no transparency attribute is evaluated
    
    The symbol is invisible.
    """
    POLYGON: 'uno.Enum'
    """
    uses the symbol given in the com.sun.star.drawing.PolyPolygonBezierCoords given in Symbol.PolygonCoords.
    """
    STANDARD: 'uno.Enum'
    """
    uses one of the standard symbols.
    
    Which standard symbol is given in Symbol.StandardSymbol.
    """

