# coding: utf-8
#
# Copyright 2023 :Barry-Thomas-Paul: Moss
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Const
# this is a auto generated file generated by Cheetah
# Libre Office Version: 7.4
# Namespace: com.sun.star.i18n
import typing


class LocaleItem(object):
    """
    Const

    These are not used with the API but with an OOo internal wrapper class that caches the contents of an instance of LocaleDataItem and uses these values to access it's members for faster access.
    
    Whenever locale data items were added these values and the wrapper class would have to be adjusted to give the application an easier access.
    
    .. deprecated::
    
        Class is deprecated.

    See Also:
        `API LocaleItem <https://api.libreoffice.org/docs/idl/ref/namespacecom_1_1sun_1_1star_1_1i18n_1_1LocaleItem.html>`_
    """
    DATE_SEPARATOR: int = 0
    THOUSAND_SEPARATOR: int = 1
    DECIMAL_SEPARATOR: int = 2
    TIME_SEPARATOR: int = 3
    TIME_100SEC_SEPARATOR: int = 4
    LIST_SEPARATOR: int = 5
    SINGLE_QUOTATION_START: int = 6
    SINGLE_QUOTATION_END: int = 7
    DOUBLE_QUOTATION_START: int = 8
    DOUBLE_QUOTATION_END: int = 9
    MEASUREMENT_SYSTEM: int = 10
    TIME_AM: int = 11
    TIME_PM: int = 12
    LONG_DATE_DAY_OF_WEEK_SEPARATOR: int = 13
    LONG_DATE_DAY_SEPARATOR: int = 14
    LONG_DATE_MONTH_SEPARATOR: int = 15
    LONG_DATE_YEAR_SEPARATOR: int = 16
    COUNT: int = 17
    """
    count of items available
    """
    DECIMAL_SEPARATOR_ALTERNATIVE: int = 17
    COUNT2: int = 18
    """
    count of items available
    """

