from .chart_shape import ChartShape as ChartShape
from .custom_presentation import CustomPresentation as CustomPresentation
from .custom_presentation_access import CustomPresentationAccess as CustomPresentationAccess
from .date_time_shape import DateTimeShape as DateTimeShape
from .document_settings import DocumentSettings as DocumentSettings
from .draw_page import DrawPage as DrawPage
from .effect_commands import EffectCommands as EffectCommands
from .effect_node_type import EffectNodeType as EffectNodeType
from .effect_preset_class import EffectPresetClass as EffectPresetClass
from .footer_shape import FooterShape as FooterShape
from .graphic_object_shape import GraphicObjectShape as GraphicObjectShape
from .handout_shape import HandoutShape as HandoutShape
from .handout_view import HandoutView as HandoutView
from .header_shape import HeaderShape as HeaderShape
from .notes_shape import NotesShape as NotesShape
from .notes_view import NotesView as NotesView
from .ole2_shape import OLE2Shape as OLE2Shape
from .outline_view import OutlineView as OutlineView
from .outliner_shape import OutlinerShape as OutlinerShape
from .page_shape import PageShape as PageShape
from .paragraph_target import ParagraphTarget as ParagraphTarget
from .presentation import Presentation as Presentation
from .presentation2 import Presentation2 as Presentation2
from .presentation_document import PresentationDocument as PresentationDocument
from .presentation_view import PresentationView as PresentationView
from .preview_view import PreviewView as PreviewView
from .shape import Shape as Shape
from .shape_animation_sub_type import ShapeAnimationSubType as ShapeAnimationSubType
from .slide_number_shape import SlideNumberShape as SlideNumberShape
from .slide_show import SlideShow as SlideShow
from .slides_view import SlidesView as SlidesView
from .subtitle_shape import SubtitleShape as SubtitleShape
from .text_animation_type import TextAnimationType as TextAnimationType
from .title_text_shape import TitleTextShape as TitleTextShape
from .transition_factory import TransitionFactory as TransitionFactory
from .x_custom_presentation_supplier import XCustomPresentationSupplier as XCustomPresentationSupplier
from .x_handout_master_supplier import XHandoutMasterSupplier as XHandoutMasterSupplier
from .x_presentation import XPresentation as XPresentation
from .x_presentation2 import XPresentation2 as XPresentation2
from .x_presentation_page import XPresentationPage as XPresentationPage
from .x_presentation_supplier import XPresentationSupplier as XPresentationSupplier
from .x_shape_event_listener import XShapeEventListener as XShapeEventListener
from .x_slide_show import XSlideShow as XSlideShow
from .x_slide_show_controller import XSlideShowController as XSlideShowController
from .x_slide_show_listener import XSlideShowListener as XSlideShowListener
from .x_slide_show_view import XSlideShowView as XSlideShowView
from .x_transition import XTransition as XTransition
from .x_transition_factory import XTransitionFactory as XTransitionFactory
