# coding: utf-8
#
# Copyright 2023 :Barry-Thomas-Paul: Moss
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Enum
# this is a auto generated file generated by Cheetah
# Namespace: com.sun.star.presentation
# Libre Office Version: 7.4
from __future__ import annotations
from typing import Protocol, Any
from typing_extensions import Literal


class ClickActionProto(Protocol):
    """Protocol for ClickAction"""

    @property
    def typeName(self) -> Literal["com.sun.star.presentation.ClickAction"]:
        ...
    value: Any
    BOOKMARK: ClickActionProto
    DOCUMENT: ClickActionProto
    FIRSTPAGE: ClickActionProto
    INVISIBLE: ClickActionProto
    LASTPAGE: ClickActionProto
    MACRO: ClickActionProto
    NEXTPAGE: ClickActionProto
    NONE: ClickActionProto
    PREVPAGE: ClickActionProto
    PROGRAM: ClickActionProto
    SOUND: ClickActionProto
    STOPPRESENTATION: ClickActionProto
    VANISH: ClickActionProto
    VERB: ClickActionProto

BOOKMARK: ClickActionProto
"""
The presentation jumps to a bookmark.
"""
DOCUMENT: ClickActionProto
"""
The presentation jumps to another document.
"""
FIRSTPAGE: ClickActionProto
"""
The presentation continues with the first page.
"""
INVISIBLE: ClickActionProto
"""
The object renders itself invisible after a click.
"""
LASTPAGE: ClickActionProto
"""
The presentation continues with the last page.
"""
MACRO: ClickActionProto
"""
A star basic macro is executed after the click.
"""
NEXTPAGE: ClickActionProto
"""
The presentation jumps to the next page.
"""
NONE: ClickActionProto
"""
use no animation effects.

use no fade effects.

No action is performed on click.
"""
PREVPAGE: ClickActionProto
"""
The presentation jumps to the previous page.
"""
PROGRAM: ClickActionProto
"""
Another program is executed after a click.
"""
SOUND: ClickActionProto
"""
A sound is played after a click.
"""
STOPPRESENTATION: ClickActionProto
"""
The presentation is stopped after the click.
"""
VANISH: ClickActionProto
"""
The object vanishes with its effect.
"""
VERB: ClickActionProto
"""
An OLE verb is performed on this object.
"""

