# coding: utf-8
#
# Copyright 2023 :Barry-Thomas-Paul: Moss
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Enum
# this is a auto generated file generated by Cheetah
# Namespace: com.sun.star.presentation
# Libre Office Version: 7.4
from __future__ import annotations
from com.sun.star import UnoEnumProto

class FadeEffectProto(UnoEnumProto):
    CLOCKWISE: UnoEnumProto
    CLOSE_HORIZONTAL: UnoEnumProto
    CLOSE_VERTICAL: UnoEnumProto
    COUNTERCLOCKWISE: UnoEnumProto
    DISSOLVE: UnoEnumProto
    FADE_FROM_BOTTOM: UnoEnumProto
    FADE_FROM_CENTER: UnoEnumProto
    FADE_FROM_LEFT: UnoEnumProto
    FADE_FROM_LOWERLEFT: UnoEnumProto
    FADE_FROM_LOWERRIGHT: UnoEnumProto
    FADE_FROM_RIGHT: UnoEnumProto
    FADE_FROM_TOP: UnoEnumProto
    FADE_FROM_UPPERLEFT: UnoEnumProto
    FADE_FROM_UPPERRIGHT: UnoEnumProto
    FADE_TO_CENTER: UnoEnumProto
    HORIZONTAL_CHECKERBOARD: UnoEnumProto
    HORIZONTAL_LINES: UnoEnumProto
    HORIZONTAL_STRIPES: UnoEnumProto
    MOVE_FROM_BOTTOM: UnoEnumProto
    MOVE_FROM_LEFT: UnoEnumProto
    MOVE_FROM_LOWERLEFT: UnoEnumProto
    MOVE_FROM_LOWERRIGHT: UnoEnumProto
    MOVE_FROM_RIGHT: UnoEnumProto
    MOVE_FROM_TOP: UnoEnumProto
    MOVE_FROM_UPPERLEFT: UnoEnumProto
    MOVE_FROM_UPPERRIGHT: UnoEnumProto
    NONE: UnoEnumProto
    OPEN_HORIZONTAL: UnoEnumProto
    OPEN_VERTICAL: UnoEnumProto
    RANDOM: UnoEnumProto
    ROLL_FROM_BOTTOM: UnoEnumProto
    ROLL_FROM_LEFT: UnoEnumProto
    ROLL_FROM_RIGHT: UnoEnumProto
    ROLL_FROM_TOP: UnoEnumProto
    SPIRALIN_LEFT: UnoEnumProto
    SPIRALIN_RIGHT: UnoEnumProto
    SPIRALOUT_LEFT: UnoEnumProto
    SPIRALOUT_RIGHT: UnoEnumProto
    STRETCH_FROM_BOTTOM: UnoEnumProto
    STRETCH_FROM_LEFT: UnoEnumProto
    STRETCH_FROM_RIGHT: UnoEnumProto
    STRETCH_FROM_TOP: UnoEnumProto
    UNCOVER_TO_BOTTOM: UnoEnumProto
    UNCOVER_TO_LEFT: UnoEnumProto
    UNCOVER_TO_LOWERLEFT: UnoEnumProto
    UNCOVER_TO_LOWERRIGHT: UnoEnumProto
    UNCOVER_TO_RIGHT: UnoEnumProto
    UNCOVER_TO_TOP: UnoEnumProto
    UNCOVER_TO_UPPERLEFT: UnoEnumProto
    UNCOVER_TO_UPPERRIGHT: UnoEnumProto
    VERTICAL_CHECKERBOARD: UnoEnumProto
    VERTICAL_LINES: UnoEnumProto
    VERTICAL_STRIPES: UnoEnumProto
    WAVYLINE_FROM_BOTTOM: UnoEnumProto
    WAVYLINE_FROM_LEFT: UnoEnumProto
    WAVYLINE_FROM_RIGHT: UnoEnumProto
    WAVYLINE_FROM_TOP: UnoEnumProto

CLOCKWISE: FadeEffectProto
"""
use the animation effect \"Clockwise\".

use the fade effect \"Clockwise\".
"""
CLOSE_HORIZONTAL: FadeEffectProto
"""
use the animation effect \"Close Horizontal\".

use the fade effect \"Close Horizontal\".
"""
CLOSE_VERTICAL: FadeEffectProto
"""
use the animation effect \"Close Vertical\".

use the fade effect \"Close Vertical\".
"""
COUNTERCLOCKWISE: FadeEffectProto
"""
use the animation effect \"Counter Clockwise\".

use the fade effect \"Counter Clockwise\".
"""
DISSOLVE: FadeEffectProto
"""
use the animation effect \"Spiral Inward Left\".

use the fade effect \"Dissolve\".
"""
FADE_FROM_BOTTOM: FadeEffectProto
"""
use the animation effect \"Fade from Bottom\".

use the fade effect \"Fade from Bottom\".
"""
FADE_FROM_CENTER: FadeEffectProto
"""
use the animation effect \"Fade from Center\".

use the fade effect \"Fade from Center\".
"""
FADE_FROM_LEFT: FadeEffectProto
"""
use the animation effect \"Fade from Left\".

use the fade effect \"Fade from Left\".
"""
FADE_FROM_LOWERLEFT: FadeEffectProto
"""
use the animation effect \"Fade from Lower Left\".

use the fade effect \"Fade from Lower Left\".
"""
FADE_FROM_LOWERRIGHT: FadeEffectProto
"""
use the animation effect \"Fade from Lower Right\".

use the fade effect \"Fade from Lower Right\".
"""
FADE_FROM_RIGHT: FadeEffectProto
"""
use the animation effect \"Fade from Right\".

use the fade effect \"Fade from Right\".
"""
FADE_FROM_TOP: FadeEffectProto
"""
use the animation effect \"Fade from Top\".

use the fade effect \"Fade from Top\".
"""
FADE_FROM_UPPERLEFT: FadeEffectProto
"""
use the animation effect \"Fade from Upper Left\".

use the fade effect \"Fade from Upper Left\".
"""
FADE_FROM_UPPERRIGHT: FadeEffectProto
"""
use the animation effect \"Fade from Upper Right\".

use the fade effect \"Fade from Upper Right\".
"""
FADE_TO_CENTER: FadeEffectProto
"""
use the animation effect \"Fade to Center\".

use the fade effect \"Fade to Center\".
"""
HORIZONTAL_CHECKERBOARD: FadeEffectProto
"""
use the animation effect \"Horizontal Checkerboard\".

use the fade effect \"Horizontal Checkerboard\".
"""
HORIZONTAL_LINES: FadeEffectProto
"""
use the animation effect \"Horizontal Lines\".

use the fade effect \"Horizontal Lines\".
"""
HORIZONTAL_STRIPES: FadeEffectProto
"""
use the animation effect \"Horizontal Stripes\".

use the fade effect \"Horizontal Stripes\".
"""
MOVE_FROM_BOTTOM: FadeEffectProto
"""
use the animation effect \"Move from Bottom\".

use the fade effect \"Move from Bottom\".
"""
MOVE_FROM_LEFT: FadeEffectProto
"""
use the animation effect \"Move from Left\".

use the fade effect \"Move from Left\".
"""
MOVE_FROM_LOWERLEFT: FadeEffectProto
"""
use the animation effect \"Move from Lower Left\".

use the fade effect \"Move from Lower Left\".
"""
MOVE_FROM_LOWERRIGHT: FadeEffectProto
"""
use the animation effect \"Move from Lower Right\".

use the fade effect \"Move from Lower Right\".
"""
MOVE_FROM_RIGHT: FadeEffectProto
"""
use the animation effect \"Move from Right\".

use the fade effect \"Move from Right\".
"""
MOVE_FROM_TOP: FadeEffectProto
"""
use the animation effect \"Move from Top\".

use the fade effect \"Move from Top\".
"""
MOVE_FROM_UPPERLEFT: FadeEffectProto
"""
use the animation effect \"Move from Upper Left\".

use the fade effect \"Move from Upper Left\".
"""
MOVE_FROM_UPPERRIGHT: FadeEffectProto
"""
use the animation effect \"Move from Upper Right\".

use the fade effect \"Move from Upper Right\".
"""
NONE: FadeEffectProto
"""
use no animation effects.

use no fade effects.

No action is performed on click.
"""
OPEN_HORIZONTAL: FadeEffectProto
"""
use the animation effect \"Open Horizontal\".

use the fade effect \"Open Horizontal\".
"""
OPEN_VERTICAL: FadeEffectProto
"""
use the animation effect \"Open Vertical\".

use the fade effect \"Open Vertical\".
"""
RANDOM: FadeEffectProto
"""
use the animation effect \"Random\".

use the fade effect \"Random\".
"""
ROLL_FROM_BOTTOM: FadeEffectProto
"""
use the fade effect \"Roll from Bottom\".
"""
ROLL_FROM_LEFT: FadeEffectProto
"""
use the fade effect \"Roll from Left\".
"""
ROLL_FROM_RIGHT: FadeEffectProto
"""
use the fade effect \"Roll from Right\".
"""
ROLL_FROM_TOP: FadeEffectProto
"""
use the fade effect \"Roll from Top\".
"""
SPIRALIN_LEFT: FadeEffectProto
"""
use the animation effect \"Spiral Inward Left\".

use the fade effect \"Spiral Inward Left\".
"""
SPIRALIN_RIGHT: FadeEffectProto
"""
use the animation effect \"Spiral Inward Right\".

use the fade effect \"Spiral Inward Right\".
"""
SPIRALOUT_LEFT: FadeEffectProto
"""
use the animation effect \"Spiral Outward Left\".

use the fade effect \"Spiral Outward Left\".
"""
SPIRALOUT_RIGHT: FadeEffectProto
"""
use the animation effect \"Spiral Outward Right\".

use the fade effect \"Spiral Outward Right\".
"""
STRETCH_FROM_BOTTOM: FadeEffectProto
"""
use the animation effect \"Stretch From Bottom\".

use the fade effect \"Stretch from Bottom\".
"""
STRETCH_FROM_LEFT: FadeEffectProto
"""
use the animation effect \"Stretch From Left\".

use the fade effect \"Stretch from Left\".
"""
STRETCH_FROM_RIGHT: FadeEffectProto
"""
use the animation effect \"Stretch From Right\".

use the fade effect \"Stretch from Right\".
"""
STRETCH_FROM_TOP: FadeEffectProto
"""
use the animation effect \"Stretch From Top\".

use the fade effect \"Stretch from Top\".
"""
UNCOVER_TO_BOTTOM: FadeEffectProto
"""
use the fade effect \"Uncover to Bottom\".
"""
UNCOVER_TO_LEFT: FadeEffectProto
"""
use the fade effect \"Uncover to Left\".
"""
UNCOVER_TO_LOWERLEFT: FadeEffectProto
"""
use the fade effect \"Uncover to Lower Left\".
"""
UNCOVER_TO_LOWERRIGHT: FadeEffectProto
"""
use the fade effect \"Uncover to Lower Right\".
"""
UNCOVER_TO_RIGHT: FadeEffectProto
"""
use the fade effect \"Uncover to Right\".
"""
UNCOVER_TO_TOP: FadeEffectProto
"""
use the fade effect \"Uncover to Top\".
"""
UNCOVER_TO_UPPERLEFT: FadeEffectProto
"""
use the fade effect \"Uncover to Upper Left\".
"""
UNCOVER_TO_UPPERRIGHT: FadeEffectProto
"""
use the fade effect \"Uncover to Upper Right\".
"""
VERTICAL_CHECKERBOARD: FadeEffectProto
"""
use the animation effect \"Vertical Checkerboard\".

use the fade effect \"Vertical Checkerboard\".
"""
VERTICAL_LINES: FadeEffectProto
"""
use the animation effect \"Vertical Lines\".

use the fade effect \"Vertical Lines\".
"""
VERTICAL_STRIPES: FadeEffectProto
"""
use the animation effect \"Vertical Stripes\".

use the fade effect \"Vertical Stripes\".
"""
WAVYLINE_FROM_BOTTOM: FadeEffectProto
"""
use the animation effect \"Wavy Line from Button\".

use the fade effect \"Wavy Line from Bottom\".
"""
WAVYLINE_FROM_LEFT: FadeEffectProto
"""
use the animation effect \"Wavy Line from Left\".

use the fade effect \"Wavy Line from Left\".
"""
WAVYLINE_FROM_RIGHT: FadeEffectProto
"""
use the animation effect \"Wavy Line from Right\".

use the fade effect \"Wavy Line from Right\".
"""
WAVYLINE_FROM_TOP: FadeEffectProto
"""
use the animation effect \"Wavy Line from Top\".

use the fade effect \"Wavy Line from Top\".
"""

