# coding: utf-8
#
# Copyright 2022 :Barry-Thomas-Paul: Moss
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Enum Class
# this is a auto generated file generated by Cheetah
# Namespace: com.sun.star.xml.xpath
# Libre Office Version: 7.3
from typing_extensions import Literal
from enum import Enum


class XPathObjectType(Enum):
    """
    Enum Class

    ENUM XPathObjectType

    See Also:
        `API XPathObjectType <https://api.libreoffice.org/docs/idl/ref/namespacecom_1_1sun_1_1star_1_1xml_1_1xpath.html#a4e7de3ae7d09203486b85490e0a6f1a3>`_
    """
    XPATH_BOOLEAN: Literal['XPATH_BOOLEAN']
    """
    """
    XPATH_LOCATIONSET: Literal['XPATH_LOCATIONSET']
    """
    """
    XPATH_NODESET: Literal['XPATH_NODESET']
    """
    """
    XPATH_NUMBER: Literal['XPATH_NUMBER']
    """
    """
    XPATH_POINT: Literal['XPATH_POINT']
    """
    """
    XPATH_RANGE: Literal['XPATH_RANGE']
    """
    """
    XPATH_STRING: Literal['XPATH_STRING']
    """
    """
    XPATH_UNDEFINED: Literal['XPATH_UNDEFINED']
    """
    """
    XPATH_USERS: Literal['XPATH_USERS']
    """
    """
    XPATH_XSLT_TREE: Literal['XPATH_XSLT_TREE']
    """
    """

