from .license_dialog import LicenseDialog as LicenseDialog
from .package_manager_dialog import PackageManagerDialog as PackageManagerDialog
from .update_required_dialog import UpdateRequiredDialog as UpdateRequiredDialog
