# coding: utf-8
#
# Copyright 2023 :Barry-Thomas-Paul: Moss
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Interface Class
# this is a auto generated file generated by Cheetah
# Libre Office Version: 7.4
# Namespace: com.sun.star.script.vba
from __future__ import annotations
import typing

from abc import ABC
if typing.TYPE_CHECKING:
    from .xvba_script_listener import XVBAScriptListener as XVBAScriptListener_533e0ff0


class XVBACompatibility(ABC):
    """

    See Also:
        `API XVBACompatibility <https://api.libreoffice.org/docs/idl/ref/interfacecom_1_1sun_1_1star_1_1script_1_1vba_1_1XVBACompatibility.html>`_
    """
    __pyunointerface__: str = 'com.sun.star.script.vba.XVBACompatibility'

    def addVBAScriptListener(self, Listener: XVBAScriptListener_533e0ff0) -> None:
        """
        """
        ...
    def broadcastVBAScriptEvent(self, Identifier: int, ModuleName: str) -> None:
        """
        """
        ...
    def removeVBAScriptListener(self, Listener: XVBAScriptListener_533e0ff0) -> None:
        """
        """
        ...

    @property
    def ProjectName(self) -> str:
        """
        """
        ...
    @ProjectName.setter
    def ProjectName(self, value: str) -> None:
        ...
    @property
    def RunningVBAScripts(self) -> int:
        """
        """
        ...
    @RunningVBAScripts.setter
    def RunningVBAScripts(self, value: int) -> None:
        ...
    @property
    def VBACompatibilityMode(self) -> bool:
        """
        """
        ...
    @VBACompatibilityMode.setter
    def VBACompatibilityMode(self, value: bool) -> None:
        ...

