from .accessible_draw_document_view import AccessibleDrawDocumentView as AccessibleDrawDocumentView
from .accessible_graph_control import AccessibleGraphControl as AccessibleGraphControl
from .accessible_graphic_shape import AccessibleGraphicShape as AccessibleGraphicShape
from .accessible_image_bullet import AccessibleImageBullet as AccessibleImageBullet
from .accessible_ole_shape import AccessibleOLEShape as AccessibleOLEShape
from .accessible_shape import AccessibleShape as AccessibleShape
from .accessible_slide_view import AccessibleSlideView as AccessibleSlideView
from .accessible_slide_view_object import AccessibleSlideViewObject as AccessibleSlideViewObject
from .alignment import Alignment as Alignment
from .applet_shape import AppletShape as AppletShape
from .arrangement import Arrangement as Arrangement
from .background import Background as Background
from .bar_code import BarCode as BarCode
from .bar_code_error_correction import BarCodeErrorCorrection as BarCodeErrorCorrection
from .bezier_point import BezierPoint as BezierPoint
from .bitmap_mode import BitmapMode as BitmapMode
from .bitmap_table import BitmapTable as BitmapTable
from .bound_volume import BoundVolume as BoundVolume
from .camera_geometry import CameraGeometry as CameraGeometry
from .canvas_feature import CanvasFeature as CanvasFeature
from .caption_escape_direction import CaptionEscapeDirection as CaptionEscapeDirection
from .caption_shape import CaptionShape as CaptionShape
from .caption_type import CaptionType as CaptionType
from .circle_kind import CircleKind as CircleKind
from .closed_bezier_shape import ClosedBezierShape as ClosedBezierShape
from .color_mode import ColorMode as ColorMode
from .color_table import ColorTable as ColorTable
from .connection_type import ConnectionType as ConnectionType
from .connector_properties import ConnectorProperties as ConnectorProperties
from .connector_shape import ConnectorShape as ConnectorShape
from .connector_type import ConnectorType as ConnectorType
from .control_shape import ControlShape as ControlShape
from .coordinate_sequence import CoordinateSequence as CoordinateSequence
from .coordinate_sequence_sequence import CoordinateSequenceSequence as CoordinateSequenceSequence
from .custom_shape import CustomShape as CustomShape
from .custom_shape_engine import CustomShapeEngine as CustomShapeEngine
from .dash_style import DashStyle as DashStyle
from .dash_table import DashTable as DashTable
from .defaults import Defaults as Defaults
from .direction3_d import Direction3D as Direction3D
from .document_settings import DocumentSettings as DocumentSettings
from .double_sequence import DoubleSequence as DoubleSequence
from .double_sequence_sequence import DoubleSequenceSequence as DoubleSequenceSequence
from .draw_page import DrawPage as DrawPage
from .draw_pages import DrawPages as DrawPages
from .draw_view_mode import DrawViewMode as DrawViewMode
from .drawing_document import DrawingDocument as DrawingDocument
from .drawing_document_draw_view import DrawingDocumentDrawView as DrawingDocumentDrawView
from .drawing_document_factory import DrawingDocumentFactory as DrawingDocumentFactory
from .ellipse_shape import EllipseShape as EllipseShape
from .enhanced_custom_shape_adjustment_value import EnhancedCustomShapeAdjustmentValue as EnhancedCustomShapeAdjustmentValue
from .enhanced_custom_shape_extrusion import EnhancedCustomShapeExtrusion as EnhancedCustomShapeExtrusion
from .enhanced_custom_shape_geometry import EnhancedCustomShapeGeometry as EnhancedCustomShapeGeometry
from .enhanced_custom_shape_glue_point_type import EnhancedCustomShapeGluePointType as EnhancedCustomShapeGluePointType
from .enhanced_custom_shape_handle import EnhancedCustomShapeHandle as EnhancedCustomShapeHandle
from .enhanced_custom_shape_metal_type import EnhancedCustomShapeMetalType as EnhancedCustomShapeMetalType
from .enhanced_custom_shape_parameter import EnhancedCustomShapeParameter as EnhancedCustomShapeParameter
from .enhanced_custom_shape_parameter_pair import EnhancedCustomShapeParameterPair as EnhancedCustomShapeParameterPair
from .enhanced_custom_shape_parameter_type import EnhancedCustomShapeParameterType as EnhancedCustomShapeParameterType
from .enhanced_custom_shape_path import EnhancedCustomShapePath as EnhancedCustomShapePath
from .enhanced_custom_shape_segment import EnhancedCustomShapeSegment as EnhancedCustomShapeSegment
from .enhanced_custom_shape_segment_command import EnhancedCustomShapeSegmentCommand as EnhancedCustomShapeSegmentCommand
from .enhanced_custom_shape_text_frame import EnhancedCustomShapeTextFrame as EnhancedCustomShapeTextFrame
from .enhanced_custom_shape_text_path import EnhancedCustomShapeTextPath as EnhancedCustomShapeTextPath
from .enhanced_custom_shape_text_path_mode import EnhancedCustomShapeTextPathMode as EnhancedCustomShapeTextPathMode
from .escape_direction import EscapeDirection as EscapeDirection
from .fill_properties import FillProperties as FillProperties
from .fill_style import FillStyle as FillStyle
from .flag_sequence import FlagSequence as FlagSequence
from .flag_sequence_sequence import FlagSequenceSequence as FlagSequenceSequence
from .generic_draw_page import GenericDrawPage as GenericDrawPage
from .generic_drawing_document import GenericDrawingDocument as GenericDrawingDocument
from .glue_point import GluePoint as GluePoint
from .glue_point2 import GluePoint2 as GluePoint2
from .gradient_table import GradientTable as GradientTable
from .graphic_export_filter import GraphicExportFilter as GraphicExportFilter
from .graphic_filter_request import GraphicFilterRequest as GraphicFilterRequest
from .graphic_object_shape import GraphicObjectShape as GraphicObjectShape
from .group_shape import GroupShape as GroupShape
from .hatch import Hatch as Hatch
from .hatch_style import HatchStyle as HatchStyle
from .hatch_table import HatchTable as HatchTable
from .homogen_matrix import HomogenMatrix as HomogenMatrix
from .homogen_matrix3 import HomogenMatrix3 as HomogenMatrix3
from .homogen_matrix4 import HomogenMatrix4 as HomogenMatrix4
from .homogen_matrix_line import HomogenMatrixLine as HomogenMatrixLine
from .homogen_matrix_line3 import HomogenMatrixLine3 as HomogenMatrixLine3
from .homogen_matrix_line4 import HomogenMatrixLine4 as HomogenMatrixLine4
from .horizontal_dimensioning import HorizontalDimensioning as HorizontalDimensioning
from .layer import Layer as Layer
from .layer_manager import LayerManager as LayerManager
from .layer_type import LayerType as LayerType
from .line_cap import LineCap as LineCap
from .line_dash import LineDash as LineDash
from .line_end_type import LineEndType as LineEndType
from .line_joint import LineJoint as LineJoint
from .line_properties import LineProperties as LineProperties
from .line_shape import LineShape as LineShape
from .line_style import LineStyle as LineStyle
from .marker_table import MarkerTable as MarkerTable
from .master_page import MasterPage as MasterPage
from .master_pages import MasterPages as MasterPages
from .measure_kind import MeasureKind as MeasureKind
from .measure_properties import MeasureProperties as MeasureProperties
from .measure_shape import MeasureShape as MeasureShape
from .measure_text_horz_pos import MeasureTextHorzPos as MeasureTextHorzPos
from .measure_text_vert_pos import MeasureTextVertPos as MeasureTextVertPos
from .mirror_axis import MirrorAxis as MirrorAxis
from .module_dispatcher import ModuleDispatcher as ModuleDispatcher
from .normals_kind import NormalsKind as NormalsKind
from .ole2_shape import OLE2Shape as OLE2Shape
from .open_bezier_shape import OpenBezierShape as OpenBezierShape
from .page_shape import PageShape as PageShape
from .plugin_shape import PluginShape as PluginShape
from .point_sequence import PointSequence as PointSequence
from .point_sequence_sequence import PointSequenceSequence as PointSequenceSequence
from .poly_line_shape import PolyLineShape as PolyLineShape
from .poly_polygon_bezier_coords import PolyPolygonBezierCoords as PolyPolygonBezierCoords
from .poly_polygon_bezier_descriptor import PolyPolygonBezierDescriptor as PolyPolygonBezierDescriptor
from .poly_polygon_bezier_shape import PolyPolygonBezierShape as PolyPolygonBezierShape
from .poly_polygon_descriptor import PolyPolygonDescriptor as PolyPolygonDescriptor
from .poly_polygon_shape import PolyPolygonShape as PolyPolygonShape
from .poly_polygon_shape3_d import PolyPolygonShape3D as PolyPolygonShape3D
from .polygon_flags import PolygonFlags as PolygonFlags
from .polygon_kind import PolygonKind as PolygonKind
from .position3_d import Position3D as Position3D
from .projection_mode import ProjectionMode as ProjectionMode
from .rectangle_point import RectanglePoint as RectanglePoint
from .rectangle_shape import RectangleShape as RectangleShape
from .rotation_descriptor import RotationDescriptor as RotationDescriptor
from .shade_mode import ShadeMode as ShadeMode
from .shading_pattern import ShadingPattern as ShadingPattern
from .shadow_properties import ShadowProperties as ShadowProperties
from .shape import Shape as Shape
from .shape_collection import ShapeCollection as ShapeCollection
from .shapes import Shapes as Shapes
from .slide_renderer import SlideRenderer as SlideRenderer
from .slide_sorter import SlideSorter as SlideSorter
from .snap_object_type import SnapObjectType as SnapObjectType
from .text import Text as Text
from .text_adjust import TextAdjust as TextAdjust
from .text_animation_direction import TextAnimationDirection as TextAnimationDirection
from .text_animation_kind import TextAnimationKind as TextAnimationKind
from .text_fit_to_size_type import TextFitToSizeType as TextFitToSizeType
from .text_horizontal_adjust import TextHorizontalAdjust as TextHorizontalAdjust
from .text_properties import TextProperties as TextProperties
from .text_shape import TextShape as TextShape
from .text_vertical_adjust import TextVerticalAdjust as TextVerticalAdjust
from .texture_kind import TextureKind as TextureKind
from .texture_kind2 import TextureKind2 as TextureKind2
from .texture_mode import TextureMode as TextureMode
from .texture_projection_mode import TextureProjectionMode as TextureProjectionMode
from .transparency_gradient_table import TransparencyGradientTable as TransparencyGradientTable
from .vertical_dimensioning import VerticalDimensioning as VerticalDimensioning
from .x_connectable_shape import XConnectableShape as XConnectableShape
from .x_connector_shape import XConnectorShape as XConnectorShape
from .x_control_shape import XControlShape as XControlShape
from .x_custom_shape_engine import XCustomShapeEngine as XCustomShapeEngine
from .x_custom_shape_handle import XCustomShapeHandle as XCustomShapeHandle
from .x_draw_page import XDrawPage as XDrawPage
from .x_draw_page_duplicator import XDrawPageDuplicator as XDrawPageDuplicator
from .x_draw_page_expander import XDrawPageExpander as XDrawPageExpander
from .x_draw_page_summarizer import XDrawPageSummarizer as XDrawPageSummarizer
from .x_draw_page_supplier import XDrawPageSupplier as XDrawPageSupplier
from .x_draw_pages import XDrawPages as XDrawPages
from .x_draw_pages_supplier import XDrawPagesSupplier as XDrawPagesSupplier
from .x_draw_sub_controller import XDrawSubController as XDrawSubController
from .x_draw_view import XDrawView as XDrawView
from .x_enhanced_custom_shape_defaulter import XEnhancedCustomShapeDefaulter as XEnhancedCustomShapeDefaulter
from .x_glue_points_supplier import XGluePointsSupplier as XGluePointsSupplier
from .x_graphic_export_filter import XGraphicExportFilter as XGraphicExportFilter
from .x_layer import XLayer as XLayer
from .x_layer_manager import XLayerManager as XLayerManager
from .x_layer_supplier import XLayerSupplier as XLayerSupplier
from .x_master_page_target import XMasterPageTarget as XMasterPageTarget
from .x_master_pages_supplier import XMasterPagesSupplier as XMasterPagesSupplier
from .x_presenter_helper import XPresenterHelper as XPresenterHelper
from .x_selection_function import XSelectionFunction as XSelectionFunction
from .x_shape import XShape as XShape
from .x_shape_aligner import XShapeAligner as XShapeAligner
from .x_shape_arranger import XShapeArranger as XShapeArranger
from .x_shape_binder import XShapeBinder as XShapeBinder
from .x_shape_combiner import XShapeCombiner as XShapeCombiner
from .x_shape_descriptor import XShapeDescriptor as XShapeDescriptor
from .x_shape_group import XShapeGroup as XShapeGroup
from .x_shape_grouper import XShapeGrouper as XShapeGrouper
from .x_shape_mirror import XShapeMirror as XShapeMirror
from .x_shapes import XShapes as XShapes
from .x_shapes2 import XShapes2 as XShapes2
from .x_shapes3 import XShapes3 as XShapes3
from .x_slide_preview_cache import XSlidePreviewCache as XSlidePreviewCache
from .x_slide_preview_cache_listener import XSlidePreviewCacheListener as XSlidePreviewCacheListener
from .x_slide_renderer import XSlideRenderer as XSlideRenderer
from .x_slide_sorter_base import XSlideSorterBase as XSlideSorterBase
from .x_universal_shape_descriptor import XUniversalShapeDescriptor as XUniversalShapeDescriptor
