# coding: utf-8
#
# Copyright 2023 :Barry-Thomas-Paul: Moss
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Enum
# this is a auto generated file generated by Cheetah
# Namespace: com.sun.star.drawing
# Libre Office Version: 7.4
from __future__ import annotations
from typing import Protocol, Any
from typing_extensions import Literal


class HorizontalDimensioningProto(Protocol):
    """Protocol for HorizontalDimensioning"""

    @property
    def typeName(self) -> Literal["com.sun.star.drawing.HorizontalDimensioning"]:
        ...
    value: Any
    AUTO: HorizontalDimensioningProto
    CENTERED: HorizontalDimensioningProto
    LEFT: HorizontalDimensioningProto
    RIGHT: HorizontalDimensioningProto

AUTO: HorizontalDimensioningProto
"""
the connection point is chosen automatically,

Set this to have the application select the best horizontal position for the text.
"""
CENTERED: HorizontalDimensioningProto
"""
The text is positioned at the center.

The text is positioned over the main line.
"""
LEFT: HorizontalDimensioningProto
"""
the connection line leaves the connected object to the left,

The left edge of the text is adjusted to the left edge of the shape.

The text is positioned to the left.
"""
RIGHT: HorizontalDimensioningProto
"""
the connection line leaves the connected object to the right,

The right edge of the text is adjusted to the right edge of the shape.

The text is positioned to the right.
"""

