# coding: utf-8
#
# Copyright 2022 :Barry-Thomas-Paul: Moss
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Enum Class
# this is a auto generated file generated by Cheetah
# Namespace: com.sun.star.xml.dom
# Libre Office Version: 7.3
from typing_extensions import Literal
from enum import Enum


class NodeType(Enum):
    """
    Enum Class

    ENUM NodeType

    See Also:
        `API NodeType <https://api.libreoffice.org/docs/idl/ref/namespacecom_1_1sun_1_1star_1_1xml_1_1dom.html#acac9cbaeea226ed297804c012dc12b16>`_
    """
    ATTRIBUTE_NODE: Literal['ATTRIBUTE_NODE']
    """
    """
    CDATA_SECTION_NODE: Literal['CDATA_SECTION_NODE']
    """
    """
    COMMENT_NODE: Literal['COMMENT_NODE']
    """
    """
    DOCUMENT_FRAGMENT_NODE: Literal['DOCUMENT_FRAGMENT_NODE']
    """
    """
    DOCUMENT_NODE: Literal['DOCUMENT_NODE']
    """
    """
    DOCUMENT_TYPE_NODE: Literal['DOCUMENT_TYPE_NODE']
    """
    """
    ELEMENT_NODE: Literal['ELEMENT_NODE']
    """
    """
    ENTITY_NODE: Literal['ENTITY_NODE']
    """
    """
    ENTITY_REFERENCE_NODE: Literal['ENTITY_REFERENCE_NODE']
    """
    """
    NOTATION_NODE: Literal['NOTATION_NODE']
    """
    """
    PROCESSING_INSTRUCTION_NODE: Literal['PROCESSING_INSTRUCTION_NODE']
    """
    """
    TEXT_NODE: Literal['TEXT_NODE']
    """
    """

