# coding: utf-8
#
# Copyright 2022 :Barry-Thomas-Paul: Moss
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Enum
# this is a auto generated file generated by Cheetah
# Namespace: com.sun.star.xml.dom
# Libre Office Version: 7.4
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    import uno
from enum import Enum

class NodeType(Enum):
    """
    Enum

    ENUM NodeType

    See Also:
        `API NodeType <https://api.libreoffice.org/docs/idl/ref/namespacecom_1_1sun_1_1star_1_1xml_1_1dom.html#acac9cbaeea226ed297804c012dc12b16>`_
    """
    typeName: str = 'com.sun.star.xml.dom.NodeType'

    ATTRIBUTE_NODE: 'uno.Enum'
    """
    """
    CDATA_SECTION_NODE: 'uno.Enum'
    """
    """
    COMMENT_NODE: 'uno.Enum'
    """
    """
    DOCUMENT_FRAGMENT_NODE: 'uno.Enum'
    """
    """
    DOCUMENT_NODE: 'uno.Enum'
    """
    """
    DOCUMENT_TYPE_NODE: 'uno.Enum'
    """
    """
    ELEMENT_NODE: 'uno.Enum'
    """
    """
    ENTITY_NODE: 'uno.Enum'
    """
    """
    ENTITY_REFERENCE_NODE: 'uno.Enum'
    """
    """
    NOTATION_NODE: 'uno.Enum'
    """
    """
    PROCESSING_INSTRUCTION_NODE: 'uno.Enum'
    """
    """
    TEXT_NODE: 'uno.Enum'
    """
    """

