# coding: utf-8
#
# Copyright 2023 :Barry-Thomas-Paul: Moss
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Enum
# this is a auto generated file generated by Cheetah
# Namespace: com.sun.star.xml.dom
# Libre Office Version: 7.4
from __future__ import annotations
from typing import Protocol, Any
from typing_extensions import Literal


class NodeTypeProto(Protocol):
    """Protocol for NodeType"""

    @property
    def typeName(self) -> Literal["com.sun.star.xml.dom.NodeType"]:
        ...
    value: Any
    ATTRIBUTE_NODE: NodeTypeProto
    CDATA_SECTION_NODE: NodeTypeProto
    COMMENT_NODE: NodeTypeProto
    DOCUMENT_FRAGMENT_NODE: NodeTypeProto
    DOCUMENT_NODE: NodeTypeProto
    DOCUMENT_TYPE_NODE: NodeTypeProto
    ELEMENT_NODE: NodeTypeProto
    ENTITY_NODE: NodeTypeProto
    ENTITY_REFERENCE_NODE: NodeTypeProto
    NOTATION_NODE: NodeTypeProto
    PROCESSING_INSTRUCTION_NODE: NodeTypeProto
    TEXT_NODE: NodeTypeProto

ATTRIBUTE_NODE: NodeTypeProto
"""
"""
CDATA_SECTION_NODE: NodeTypeProto
"""
"""
COMMENT_NODE: NodeTypeProto
"""
"""
DOCUMENT_FRAGMENT_NODE: NodeTypeProto
"""
"""
DOCUMENT_NODE: NodeTypeProto
"""
"""
DOCUMENT_TYPE_NODE: NodeTypeProto
"""
"""
ELEMENT_NODE: NodeTypeProto
"""
"""
ENTITY_NODE: NodeTypeProto
"""
"""
ENTITY_REFERENCE_NODE: NodeTypeProto
"""
"""
NOTATION_NODE: NodeTypeProto
"""
"""
PROCESSING_INSTRUCTION_NODE: NodeTypeProto
"""
"""
TEXT_NODE: NodeTypeProto
"""
"""

