from .xml_document_wrapper import XMLDocumentWrapper as XMLDocumentWrapper
from .xml_element_wrapper import XMLElementWrapper as XMLElementWrapper
from .xxml_document_wrapper import XXMLDocumentWrapper as XXMLDocumentWrapper
from .xxml_element_wrapper import XXMLElementWrapper as XXMLElementWrapper
