# coding: utf-8
#
# Copyright 2022 :Barry-Thomas-Paul: Moss
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Const
# this is a auto generated file generated by Cheetah
# Libre Office Version: 7.4
# Namespace: com.sun.star.rendering
from typing_extensions import Literal
"""
Const


See Also:
    `API PanoseContrast <https://api.libreoffice.org/docs/idl/ref/namespacecom_1_1sun_1_1star_1_1rendering_1_1PanoseContrast.html>`_
"""
ANYTHING: Literal[0]
NO_FIT: Literal[1]
NONE: Literal[2]
VERY_LOW: Literal[3]
LOW: Literal[4]
MEDIUM_LOW: Literal[5]
MEDIUM: Literal[6]
MEDIUM_HIGH: Literal[7]
HIGH: Literal[8]
VERY_HIGH: Literal[9]

